### ISSUE TITLE
Empty repo created!

### ISSUE THREAD

**Issue by jonnyhtw** [jonnyhtw/gitlaboratary#1]
Hi @pletzer!

I've created the empty repo as discussed earlier at Hacky Hour so feel free to add some kind of simple file for us!

Many thanks

Jonny

**Comment by pletzer** [comment]
I just modified the README and created a pull-request.

**Comment by jonnyhtw** [comment]
OK super thanks. 

I'll investigate what I need to do next as I haven't done this before! :smile:

**Comment by jonnyhtw** [comment]
Done :smile: 

Closing issue.
